version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - projeto-votacao

networks:
  projeto-votacao:
    driver: bridge
