version: "3"

services:
  db:
    image: mysql:latest
    container_name: votacao-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - votacao
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: votacao
    container_name: votacao-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - votacao
    ports:
      - '5173:5173'

  nginx:
    image: nginx:1.17-alpine
    container_name: votacao-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - votacao

networks:
  votacao:
    driver: bridge
